### ISSUE TITLE
code in dark mode

### ISSUE THREAD

**Issue by benatkin** [bangle-io/bangle-io-issues#3]
go to https://bangle.io/ws/bangle-help and type ```test

<img width="796" alt="Captura de Pantalla 2021-07-08 a la(s) 12 48 06" src="https://user-images.githubusercontent.com/4126/124981725-c11a4e00-dfea-11eb-85e0-433a8803b06b.png">

**Comment by kepta** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/6966254/125239689-dec30e00-e29d-11eb-9f2c-6be9bc30c051.png">

This was fixed. Thanks for reporting
